### PR TITLE
[refs #00178] Replace logo

### PR DESCRIPTION
**Pull request by Android63**
Use larger NHS leadership Academy logo as shown in this screenshot:

screen shot 2017-12-08 at 11 50 53

### CODE REVIEW

**Review by cehwitham — COMMENTED** [review]
What's the file naming convention we're using?

**Comment by Android63** [comment]
As far as I know, there is no file-naming convention @cehwitham - apart from we add @2x to indicate a retina image. Logos can be uploaded by site admins and I guess they'll have all sorts of file names and locations.

**Comment by cehwitham** [comment]
@Android63 but within our files, we should keep a consistent naming approach.

All lowercase with - separators seems to be what we've done until now.

**Comment by penpadstudio** [comment]
@cehwitham I try to stick to a BEM but its quite loosely on the design files. @Android63 if you feel the need to be more ridged in the approach please feel free to edit.

**Comment by penpadstudio** [comment]
@cehwitham I use underscores and title case on design files.

**Comment by Android63** [comment]
I see what you mean @cehwitham. The CAPITAL LETTERS stand out like a sore thumb. Will use lowercase with - separators to keep things consistent.

**Comment by Android63** [comment]
I've renamed the logos using the same naming conventions as the code files, and have used -- to keep with the BEM convention we've been using in CSS.

**Comment by Android63** [comment]
Could you review this again please @cehwitham?

**Review by cehwitham — APPROVED** [review]

**Pull request merged**
