### PR TITLE
IE8 Fixes

### PR DESCRIPTION
**Pull request by csswizardry**
For the most part, IE8 looks really respectable! There are some cosmetic issues remaining that we should discuss (i.e. is it going to be financially viable to fix _everything_) and a couple of leftovers that I expect to be fixed as part of other tasks.

### CODE REVIEW

**Review by cehwitham — APPROVED** [review]
Out of curiosity, is it IE8 related or something else why `&::hover` has changed to `&:hover`?

**Comment by csswizardry** [comment]
@cehwitham: There shouldn’t be any `::hover` specifically, as that’s never been a thing. Did you see `::hover` or was that a typo? To answer the question more generally, please see ffb2d522e 👍

**Comment by cehwitham** [comment]
I saw ~~`::hover`~~ `::before`had been removed in a lot of places but I think it's answered by:

> OldIE doesn’t support the `::(before|after)` double-colon syntax.
> Dropping back to single colons seems to fix, well, a lot!


As you said.

**Comment by csswizardry** [comment]
I think/hope you’ve seen `::before` and `::after`, and not `::hover`, though. If there are any `::hover`s in there, it’s a typo!

Edit: Just checked. I think it’s just a persistent typo on your part haha. There were/are no double-colon `::hover` pseudos :)

**Pull request merged**
