### PR TITLE
Update button styles

### PR DESCRIPTION
**Pull request by csswizardry**

### CODE REVIEW

**Comment by csswizardry** [comment]
https://d3vv6lp55qjaqc.cloudfront.net/items/0i1X1J3J2E2I3D0i3V3D/Screen%20Recording%202017-08-23%20at%2005.53%20pm.gif?X-CloudApp-Visitor-Id=138442&v=edf35cc1

**Comment by penpadstudio** [comment]
@csswizardry so I have attempted to update some of the css. please review and check.
Also noticed some things probably would take me a lot longer than yourself.
- a bug on focus state on hover. seems strange to me. Focus state should not stay active after click or tap release.
- also move down font by one pixel I think as seems out of place especially on focus state.

**Comment by csswizardry** [comment]
@Pro-Paul:

> a bug on focus state…

Fixed this by swapping `:focus` to `:active`. This means that the depressed state no longer persists, but also means that we lose the depressed state on keyboard focus (instead, we get the browser default blue outline).

> also move down font by one pixel…

I don’t know if you remember way back at the beginning: we had this issue before we moved to a webfont… The problem lies in the font itself (it’s set too high on its baseline) and isn’t something we can do anything about 😢

**Comment by csswizardry** [comment]
Ping @Pro-Paul, @cehwitham.

**Comment by cehwitham** [comment]
Bottom margins on the none full width buttons doesn't seem to work on mobile?

Looks fine on horizontal iPhone but not vertical iPhone. 

image uploaded from ios

**Comment by penpadstudio** [comment]
Also on tap on mobile we don't get to see the pressed state of the buttons.

**Comment by csswizardry** [comment]
@cehwitham: Yeah, none of the buttons actually carry margins; it’s just that the full-width ones are wrapped in their own `<p>` elements to force them to stack.

@Pro-Paul: On mobile, we only get the `:hover` state. Unfortunately, I’m not 100% sure why this is, but I made a reduced test case and it seems that—on iOS at least—`:active` and `:focus` are ignored, and only the `:hover` styles get used. Please feel free to dive in and make any changes.

**Review by cehwitham — APPROVED** [review]

**Review by penpadstudio — APPROVED** [review]

**Pull request merged**
