### PR TITLE
Miscellaneous UI Tweaks

### PR DESCRIPTION
**Pull request by csswizardry**

### CODE REVIEW

**Review by penpadstudio — COMMENTED** [review]
NHS logo should not be transparent, should be opaque white for the typeface.

**Review by chriscoffee — APPROVED** [review]
Nice one man, good spot with the whitespace I left. Divider makes more sense than splitter given it's dividing as oppose to splitting but generally called a splitter?! Also got to love the glipc alignment

**Comment by penpadstudio** [comment]
Also what are the better sizing rules you have set for the logo?

**Comment by csswizardry** [comment]
@p5uln: Cool! Wanna open an issue for it and grab me an original copy of the logo? Not sure where I actually grabbed this one from.

> Also what are the better sizing rules you have set for the logo?

This wasn’t a design change, it was just about how I was writing the code for it. It’s important to remember that this HTML page is just a dumping ground, so isn’t intended to look neat and tidy yet. If you can point me in the direction of an original, and at what size you’d like it to appear, I can get it implemented :)

**Pull request merged**
