### PR TITLE
Add tabs component

### PR DESCRIPTION
**Pull request by csswizardry**
Initial styling of tabs components is done. Should be okay to merge, but
will await feedback.

### CODE REVIEW

**Comment by csswizardry** [comment]
In t’code:

image

**Comment by penpadstudio** [comment]
need to create breakpoint for text to switch to icons for mobile. 
should be a six tab system max.
also can we reflect disabled states.
icons should be #425563 same as text inactive state.
unable to switch tab highlight currently.

**Comment by csswizardry** [comment]
> need to create breakpoint for text to switch to icons for mobile.

Will discuss this; sounds like it’s more of a ‘we need container queries’ problem, unfortunately.

> should be a six tab system max.

That’s fine; this shows five tabs, we can put more in, we can put less in. This is a content problem, not a Nightingale problem.

> also can we reflect disabled states.

Yep!

> icons should be #425563 same as text inactive state.

You’re in charge of icons 👍 

> unable to switch tab highlight currently.

Not sure what you mean by this. The highlighted state is controlled by the `.is-current` class.

**Comment by csswizardry** [comment]
Tabs now have regular, current, and disabled states:

**Small screen:**

image

**Large screen:**

image

**Comment by csswizardry** [comment]
@Pro-Paul, @cehwitham: Whenever you get a chance, can you give this a once-over, please?

**Review by penpadstudio — APPROVED** [review]
Happy to merge in at current level of build.

**Pull request merged**
