### PR TITLE
Add hint utilities

### PR DESCRIPTION
**Pull request by csswizardry**
I’ve implemented a mechanism whereby developers are instantly notified in their HTML as soon as they misimplement a class or feature.

### CODE REVIEW

**Comment by cehwitham** [comment]
When we `deploy` this, does it automatically turn hints off?

**Comment by csswizardry** [comment]
@cehwitham: It’s up to you; would you rather have them on or off by default? Currently, they’re enabled by default, but they’re behind a feature switch that the developer would (en|dis)able as necessary.

EDIT: Ohhhh! I understand the question now. Hopefully, we’d not be trying to deploy anything that’s full of red boxes anyway, but we could maybe get @chriscoffee to look at getting the build process to completely disable them 👍

**Comment by cehwitham** [comment]
@csswizardry think on as default is a good approach for developing so they're more easily discovered. I was more meaning could we flag it in the `npm run deploy` command so that it gets turned off but as you say, possibly something for @chriscoffee to consider and would probably change if we implement Gulp.

**Review by cehwitham — APPROVED** [review]

**Comment by chriscoffee** [comment]
Is it possible to render them on screen with `@error/@warn` directives rather than pseudoclasses?

**Comment by csswizardry** [comment]
`@error` and `@warn` get passed to the output stream (stdout), not to any kind of file.

**Pull request merged**
