### PR TITLE
Add breadcrumb component

### PR DESCRIPTION
**Pull request by csswizardry**

### CODE REVIEW

**Comment by cehwitham** [comment]
On all screen sizes, the breadcrumb links get cropped by the containing box. I'm not sure if this is the desired behaviour or whether we need to resolve this?

screen shot 2017-08-11 at 11 02 43

**Comment by penpadstudio** [comment]
@cehwitham this is on purpose. Its a scrolling breadcrumb bar. Maybe a fade would be better suited so not to give the wrong impression? @csswizardry

**Comment by cehwitham** [comment]
@Pro-Paul ah I see how the works now. How does that present on Windows? It works quite nicely as a two finger scroll on Mac. Do you get ugly scrollbars on windows? Do you think people will understand that functionality?

+1 for a fade if we want to follow this up.

**Comment by jdbrew** [comment]
Do you remember the activity completion graph we did in NHSx @cehwitham ?! 
It was big and scrolled in all directions and we happily used it on Mac and touch devices .... Windows users however could not use it at all and we had to overhaul the design to compensate.

Mac and touch people just moved around pages in 2 dimensions. Windows users move in 1 dimension, at a push, and almost all just assumed it was broken! Those that knew it scrolled could not figure out how to scroll in the vertical.

Good bit of learning about scrolling behaviours on different platforms.

**Comment by csswizardry** [comment]
> Maybe a fade would be better suited…

> +1 for a fade if we want to follow this up.

I put one in immediately for the exact reasons we’ve seen, but the fade (for some baffling reason) scrolls with the list. Even when positioned absolutely, it still moves. Can explore if we want me to spend more time on it 👍

**Comment by cehwitham** [comment]
Let's not spend too much time on this now @csswizardry.

@Pro-Paul could you setup some user testing for this component, please?

**Comment by csswizardry** [comment]
> Let's not spend too much time on this now @csswizardry.

Thanks. I agree. Don’t want a fade to end up costing half a day haha. I opened the PR without it because it was already getting unreasonably expensive.

**Review by cehwitham — APPROVED** [review]

**Pull request merged**
