### PR TITLE
[refs #00222] Remove live ribbon

### PR DESCRIPTION
**Pull request by Android63**
Remove "live" ribbon markup from example page.

### CODE REVIEW

**Review by cehwitham — COMMENTED** [review]
Why don't we need this any more?

**Comment by Android63** [comment]
@cehwitham according to https://github.com/NHSLeadership/nightingale/issues/222 @Pro-Paul said we should have removed Live prototype ribbon. Not sure why.

**Comment by cehwitham** [comment]
@Pro-Paul could you confirm please and then we can remove.

**Comment by penpadstudio** [comment]
@cehwitham Live ribbon is removed as we do not need to state that its live only that the pages are in development with Alpha and Beta. Its a GDS pattern.

**Comment by penpadstudio** [comment]
@cehwitham @Android63 is there any code reason as to why we can't merge this update to update and have the Live ribbon removed from the framework?

**Pull request merged**
