### PR TITLE
Comment forms and threads/listings

### PR DESCRIPTION
**Pull request by csswizardry**

### CODE REVIEW

**Comment by csswizardry** [comment]
**Regular comment form:**

image

**Expanded comment form:**

image

**Comment threads:**

image

**Review by cehwitham — APPROVED** [review]

**Comment by cehwitham** [comment]
Well `&#{&}` is a really nice trick. Like it.

**Review by penpadstudio — COMMENTED** [review]
comment field look fine to me, as discussed previously the initial comment field box should expand to full features. Also noticed secondary button probably needs updating to NHS blue font.

**Comment by cehwitham** [comment]
> the initial comment field box should expand to full features

This should be implementation I think so something for @ishanivardhan and @Android63 to be aware of.

> secondary button probably needs updating to NHS blue font.

Good spot!

**Comment by csswizardry** [comment]
> …as discussed previously the initial comment field box should expand to full features.

Yep, and as I said at the time (and @cehwitham reiterated above), that would be implementation detail governed by the platform.

> Also noticed secondary button probably needs updating to NHS blue font.

Yeah, that’s a separate issue that can be solved as another task. Is there an actual issue open for restyling the buttons?

**Pull request merged**
