### PR TITLE
[refs #00116] Add footer nav

### PR DESCRIPTION
**Pull request by csswizardry**
The footer has a small nav in it; this commit instates that nav.

### CODE REVIEW

**Comment by ishanivardhan** [comment]
@csswizardry - Looks good ! Just checked it's responsiveness and this is how it would look on phones (tried iPhone 6 resolution). Is that right?

screen shot 2017-08-08 at 17 16 47

**Comment by csswizardry** [comment]
Dang! Good spot, sorry! Will fix. Thank you!`</embarrassed>`

**Comment by csswizardry** [comment]
Fix incoming!

image

**Comment by ishanivardhan** [comment]
Looks good now @csswizardry ! We can potentially merge this but not sure if we should wait for the Circle CI issue to be fixed? Maybe until tomorrow.

**Comment by csswizardry** [comment]
> Maybe until tomorrow.

Yeah, I think leave it until @chriscoffee can cast his eyes over it, ideally. We can always consume the `tkt-00116` branch to get these changes ahead of time if we need them sooner :)

**Comment by chriscoffee** [comment]
Tests are passing now. @csswizardry.  I've made a ticket to clean up some other things but atleast the tests are a passing now. Issue related to Slack notifications being removed which has now been corrected.

**Comment by cehwitham** [comment]
I'm happy for this to be merged now @csswizardry @ishanivardhan

**Pull request merged**
