### PR TITLE
Add icons

### PR DESCRIPTION
**Pull request by csswizardry**
This large PR introduces our image sprite and methods for generating and implementing icons out of them.

### CODE REVIEW

**Comment by cehwitham** [comment]
When I pulled down the branch and ran `npm run watch` the correct styles weren't compiled until I went and saved a change in the main.scss file. Should we have a command to do an initial build of the CSS when you pull down the repo so you can test without triggering sass watch?

**Comment by cehwitham** [comment]
@csswizardry do we have a Sketch file to generate the sprite PNGs?

**Comment by csswizardry** [comment]
@cehwitham: Regarding the Sass… this is an issue that I’m aware of and keen to fix, but I’m not sure what the cleanest way to achieve it is without repeating lots of code in the npm scripts. You are right though: it needs addressing.

Regarding the Sketch file, Paul has an artboard set up just for icons in the main FEF Sketch file. It exports nice and cleanly, including retina stuff.

**Comment by cehwitham** [comment]
@csswizardry In our [Nightingale Moodle theme](https://github.com/NHSLeadership/theme_nhsla_nightingale/blob/master/package.json) setup, the `watch` command calls `build` so you can either build the CSS after cloning the repo, or running watch will build the CSS without any file changes too. Might be a simple way to solve it?

We're also thinking about implementing Gulp as an alternative so we can make use of some more automated setup stuff on install. Might be worth considering? @chriscoffee set it up and then removed it from some of our stuff because it wasn't performant enough for his liking. But now he's making the recommendation.

Re Sketch - I always forget this is a separate repo but makes sense. Cheers.

**Comment by csswizardry** [comment]
@cehwitham: Yeah, I know it’s absolutely doable, but I just haven’t yet because a quick fix would lead to a lot of duplication. Just need to set some time aside to fix it properly.

> …it wasn't performant enough for his liking.

It was probably a few nanoseconds too far north of 0.00001s 😉

Do we see anything blocking this particular PR?

**Review by cehwitham — APPROVED** [review]

**Pull request merged**
