### PR TITLE
[refs #00098] Alter font-stack

### PR DESCRIPTION
**Pull request by csswizardry**

### CODE REVIEW

**Comment by penpadstudio** [comment]
not sure what this is but page load not working for me:

screen shot 2017-08-14 at 13 57 01

**Comment by csswizardry** [comment]
> not sure what this is but page load not working for me:

Whoa! I have no idea what’s causing this. It did sneak in in the last commit though. Investigating. Good spot!

**Comment by csswizardry** [comment]
Okaaaaaay. This is _odd_.

There’s a Safari bug whereby any text following a `details`/`summary` element will be rendered incorrectly if that `summary`/`details` element’s text is sized with rems. This is true until the region(s) in question repaint(s). When using a webfont, we do get an inherent repaint once the font loads, which is why we never saw the issue manifest before. Now that we’ve got rid of the webfont, we’ve got rid of the repaint, and now we witness this issue.

Not really sure what to do here…

**Review by cehwitham — APPROVED** [review]

**Comment by csswizardry** [comment]
Regarding 5d0bf38:

**Before:**

image


**After:**

image

**Pull request merged**
