### PR TITLE
Add Panels component

### PR DESCRIPTION
**Pull request by csswizardry**
Cosmetically I think the Panels are pretty much there. We’ll likely need to tweak small things as we drop real content into them, but for now, they feel good enough to merge in.

### CODE REVIEW

**Review by cehwitham — COMMENTED** [review]
```css
Kinda gross, but… we need to remove leftover style from nested DIVs 
* in regular DETAILS elements (_elements.details.scss).
```

Is this an indication we need to refactor the detail element?

Are we including the programme logos for the demo or to use in prod? I see they're being used as `` so we can write these into the markup which is great. If they're just for the demo, should we just have 1? Thinking about the balance between vanilla framework and usable product.

The cpanel controls don't seem to allow me to move between the 5 different panels, should this be working?

**Comment by csswizardry** [comment]
> Is this an indication we need to refactor the detail element?

Not yet. Run into a problem once, grin and bear it; run into a problem twice, refactor :)

> The panel controls don't seem to allow me to move between the 5 different panels, should this be working?

It’s intentionally non-functional at the moment until we know what (if any) plugin we’ll use to power it. My JS is weak enough that I’m trying to de-prioritise stuff like that until we have a use-case for it; focus on getting the styling side of things nailed first :)

**Comment by cehwitham** [comment]
@csswizardry good advice and good answer. If the tests pass, I'm happy for this to be merged.

**Review by cehwitham — APPROVED** [review]

**Comment by cehwitham** [comment]
@csswizardry any thoughts on my logo questions?

**Comment by csswizardry** [comment]
> …any thoughts on my logo questions?

Ooops! Sorry.

> Are we including the programme logos for the demo or to use in prod? […] If they're just for the demo, should we just have 1? Thinking about the balance between vanilla framework and usable product.

I’ve built a general solution for the image, so that means we can use anything at all. Ergo, this really is just a demo, so I’ll whip the other logos back out. Good spot 😃

**Comment by penpadstudio** [comment]
1. Can we change naming convention from 'Panels' to 'Media' ? (referring to original sketch artboards Media encompasses all video audio and imagery elements and Panels refer to sticky posts, media combined with buttons etc...) Unless there is a valid reason to change?
2. Image tag descriptor should use Comments para style (14 px, #425563).
3. 4th element, should not have title and copy in lower box unless it is transcript with video element? Even then the title should only be visible on default with dropdown for copy with a scroll function. * if possible may even substitute this feature for the CC button on video playback.
4. Also issue with purple tint stretching on resize:
screen shot 2017-08-10 at 11 05 54
screen shot 2017-08-10 at 11 07 23
5. There are more Media elements that are not here, here is the latest full list (leave transcript till last as previous comment):
screen shot 2017-08-10 at 11 09 57
screen shot 2017-08-10 at 11 10 10
screen shot 2017-08-10 at 11 10 25
screen shot 2017-08-10 at 11 10 20

**Comment by csswizardry** [comment]
> Can we change naming convention from 'Panels' to 'Media' ?

Media and Panels look to be very much the same in terms of design style, so they need to be called the same thing in the code (so that we can reuse it).

image

Would you rather we switch them all over to Media?

> Image tag descriptor should use Comments para style (14 px, #425563).

Yikes! My bad. Good catch. Apologies. **UPDATE:** Done in 1ee7b5a

> 4th element, should not have title and copy in lower box unless it is transcript with video element?

Yeah, I’m keen to reiterate that we shouldn’t be getting bogged down with implementation detail in this repo, as this repo isn’t an implementation of Nightingale: it’s just everything assembled in the abstract. If you dig around the code you’ll see that everything is assembled from much smaller parts. Try to look past how this demo page is put together, if you can—it’s pretty abstract.

> Also issue with purple tint stretching on resize…

Good spot! This occurs when the media uploaded doesn’t match the aspect ratio of its container. I think this should be a trivial fix for newer browsers, but for older ones we’ll have to be mindful of aspect ratios etc. **UPDATE:** Done in 8fc3eae

> There are more Media elements that are not here…

Again, these can all be assembled by what we have already.

- - -

Regarding video stuff, I’d recommend seeing how far we get with vanilla `video` elements before designing a custom video player.

**Comment by penpadstudio** [comment]
>Media and Panels look to be very much the same in terms of design style, so they need to be called the same thing in the code (so that we can reuse it).

Makes sense I guess.

>Would you rather we switch them all over to Media?

Yes, I think Media is more appropriate and it leave Panels open for other elements.

>Yeah, I’m keen to reiterate that we shouldn’t be getting bogged down with implementation detail in this repo, as this repo isn’t an implementation of Nightingale: it’s just everything assembled in the abstract. If you dig around the code you’ll see that everything is assembled from much smaller parts. Try to look past how this demo page is put together, if you can—it’s pretty abstract.

I don't follow maybe a discussion for Monday, and also discussing the below too.

>Regarding video stuff, I’d recommend seeing how far we get with vanilla video elements before designing a custom video player.

**Comment by csswizardry** [comment]
> I don't follow…

In the HTML page that you’re viewing, I’m not demonstrating every single iteration of every single component because that would take forever to build. What I am doing is building all of the little parts and demonstrating more complex combinations. Don’t stress too much if _Part X shouldn’t be inside of Part Y_: the key thing to focus on is that all of the relevant parts are there. They can be reconfigured into the correct order when we need them.

> Yes, I think Media is more appropriate

Renaming now 👍

**Pull request merged**
